name: Starling

on:
  push:
    branches: [ "read-the-docs" ]
  pull_request:
    branches: [ "read-the-docs" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
      uses: snok/install-poetry@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - name: Install project
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --with docs,dev --no-interaction
    - uses: isort/isort-action@v1
    - uses: psf/black@stable
      with:
        options: "--check --verbose"
        src: "./starling"
    - name: Pytest
      run: |
        poetry run pytest
    - name: Build documentation
      run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/source
          poetry run sphinx-build -b html . ../build
          cp -r ../build/* ../../gh-pages/
    - name: Deploy documentation
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: gh-pages
